name: Primer workflow

on: push

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "HOLA ACTIONS"

      - name: Bajar codigo
        uses: actions/checkout@v4

      - name: Probar codigo
        run: python3 main.py
