name: Primer workflow

on: push

jobs:
 validar:
  runs-on: ubuntu-latests

  steps:
   - name: Mostrar mensaje
     run: echo "HOLA ACTIONS"
     
   - name: Bajar codigo
     uses: actions/checkout

   - name: Probar codigo
   - run: python3 main.py
